/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringMain */

#ifndef _Included_StringMain
#define _Included_StringMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringMain
 * Method:    StringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringMain_StringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     StringMain
 * Method:    Reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringMain_Reverse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
