/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeArithmetic */

#ifndef _Included_NativeArithmetic
#define _Included_NativeArithmetic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeArithmetic
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeArithmetic_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeArithmetic
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeArithmetic_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeArithmetic
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeArithmetic_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeArithmetic
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeArithmetic_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
